-- MySQL Script generated by MySQL Workbench
-- Sun 04 Mar 2018 13:27:37 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spa_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `spa_db` ;

-- -----------------------------------------------------
-- Schema spa_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spa_db` DEFAULT CHARACTER SET utf8 ;
USE `spa_db` ;

-- -----------------------------------------------------
-- Table `spa_db`.`seeds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spa_db`.`seeds` ;

CREATE TABLE IF NOT EXISTS `spa_db`.`seeds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seed` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spa_db`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spa_db`.`clients` ;

CREATE TABLE IF NOT EXISTS `spa_db`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aid` VARCHAR(32) NULL,
  `password` VARCHAR(32) NULL,
  `seed` INT NULL,
  `old_seed` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_clients_1_idx` (`seed` ASC),
  INDEX `fk_clients_2_idx` (`old_seed` ASC),
  INDEX `index5` (`aid` ASC),
  CONSTRAINT `fk_clients_1`
    FOREIGN KEY (`seed`)
    REFERENCES `spa_db`.`seeds` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_2`
    FOREIGN KEY (`old_seed`)
    REFERENCES `spa_db`.`seeds` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spa_db`.`randoms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spa_db`.`randoms` ;

CREATE TABLE IF NOT EXISTS `spa_db`.`randoms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `random` DOUBLE(15,14) NULL,
  `seed` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_randoms_1_idx` (`seed` ASC),
  CONSTRAINT `fk_randoms_1`
    FOREIGN KEY (`seed`)
    REFERENCES `spa_db`.`seeds` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
